
networks:
  internal:
    driver: bridge
  default:
    driver: bridge

volumes:
  app:
    driver: local
    driver_opts:
      type: none
      device: ./
      o: bind
  db_data:
    driver: local
    driver_opts:
      type: none
      device: ./.data
      o: bind

services:
  app:
    image: php:8.3-fpm
    working_dir: /var/www
    # user: ${HOST_UID}:${HOST_GID}
    entrypoint: ["bash", "-c", "docker-php-ext-install pdo pdo_mysql mysqli && apt-get update && apt-get install -y libzip-dev zip unzip git && php artisan migrate && php-fpm"]
    volumes:
      - app:/var/www
    depends_on:
      - db
    networks:
      - internal
      - default

  nginx:
    image: nginx:latest
    working_dir: /var/www/
    tty: true
    volumes:
      - app:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    entrypoint: ["nginx"]
    depends_on:
      - app
    networks:
      - default

  db:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/:/docker-entrypoint-initdb.d
    ports:
      - "${DB_PORT}:3306"
    networks:
      - internal
