name: Laravel Docker CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker Compose
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker Compose
      run: |
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Set up Docker environment variables
      run: |
        echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> $GITHUB_ENV
        echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> $GITHUB_ENV
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
        echo "DB_PORT=3306" >> $GITHUB_ENV

    - name: Build and start Docker containers
      run: |
        docker-compose -f docker-compose.yml up -d

    - name: Wait for the MySQL database to be ready
      run: |
        until docker exec -i $(docker ps -qf "name=db") mysqladmin --user=root --password=root --host=localhost --port=3306 ping --silent; do
          echo "Waiting for MySQL to be ready..."
          sleep 5
        done

    # Install Composer in the app container
    - name: Install Composer in the app container
      run: |
        docker exec $(docker ps -qf "name=app") bash -c "curl -sS https://getcomposer.org/installer | php"
        docker exec $(docker ps -qf "name=app") bash -c "mv composer.phar /usr/local/bin/composer"

    # Install Composer dependencies inside the app container
    - name: Install Composer dependencies
      run: |
        docker exec $(docker ps -qf "name=app") bash -c "composer install --no-interaction --prefer-dist"

    - name: Run tests inside the app container
      run: |
        docker exec $(docker ps -qf "name=app") bash -c "php artisan migrate --force && php artisan test"

    - name: Shutdown Docker containers
      run: |
        docker-compose down

